name: inventory-control
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: owner/inventory-control
    build_command: npm ci && npm run build
    run_command: npm start
    envs:
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: NODE_ENV
        scope: RUN_TIME
        value: "production"
      - key: VITE_SUPABASE_URL
        scope: RUN_TIME
        value: ${VITE_SUPABASE_URL}
      - key: VITE_SUPABASE_ANON_KEY  
        scope: RUN_TIME
        value: ${VITE_SUPABASE_ANON_KEY}
      - key: VITE_PG_HOST
        scope: RUN_TIME
        value: ${VITE_PG_HOST}
      - key: VITE_PG_PORT
        scope: RUN_TIME
        value: ${VITE_PG_PORT}  
      - key: VITE_PG_DATABASE
        scope: RUN_TIME
        value: ${VITE_PG_DATABASE}
      - key: VITE_PG_USER
        scope: RUN_TIME
        value: ${VITE_PG_USER}
      - key: VITE_PG_PASSWORD
        scope: RUN_TIME
        value: ${VITE_PG_PASSWORD}
      - key: VITE_PG_SSL
        scope: RUN_TIME
        value: ${VITE_PG_SSL}
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
      port: 8080
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3